[content]
enableCraftingPad = true
enableDynamite = true
enableSlimeBucket = true
enableFriedEgg = true
enableStorageBlocks = true
enablePedestal = true
dynamiteCooldown = 20
dynamiteExplosionPower = 3
[enchanting]
enableBlazing = true
enableHops = true
enableNimble = true
enableSiphon = true
enableVeteran = true
enableVigor = true
enableHoming = true
blazingTreasureOnly = false
hopsTreasureOnly = true
nimbleTreasureOnly = false
siphonTreasureOnly = false
veteranTreasureOnly = false
vigorTreasureOnly = false
homingTreasureOnly = false
[loot]
batLeatherDropChance = 1.0
namedMobsDropNameTag = false
[tweaks]
enableArmorStandSwapping = true
itemFrameRotateBackwards = true
babyZombieBurnInDaylight = true
creeperBurnInDaylight = true
shearOffNameTag = true
hoeActsAsSickle = true
tntIgnition = true
enableSilkSpawner = true
[world]
realisticRelationship = true
disableLavaPockets = true
selfPlanting = true
selfPlantingInterval = 100
selfPlantingBlackList = []
[recipe]
betterChestRecipe = true
betterRepeater = true
betterTrappedChestRecipe = true
woolToString = true
nameTag = false
